Convert 3 pages into HTML styling.
momentum-mod/blog pull request #3
Opened 2022-06-23 09:25 UTC by tmob03

Three pages weren't in HTML, therefore they did not display correctly on https://blog.momentum-mod.org/.

2022-06-23 09:30 UTC, tmob03 commented
Another thing I thought of doing was going around and uploading all the images into the posts to this repo to make sure they don't become dead, although this might be overkill, should I?

2022-10-01 01:41 UTC, tmob03 commented
@Gocnak Review please ^^?

2022-10-01 06:23 UTC, Gocnak requested changes

2022-10-01 06:23 UTC, Gocnak commented on content/posts/imported/2016-03-03-welcome.md
> +If you want to get involved in development, <a href="http://momentum-mod.org/contact"> contact us here!</a> Please include some sort of past work or proof of skills. We're accepting programmers, sour
This link is no longer relevant, please change to our discord:

```suggestion
If you want to get involved in development, <a href="https://discord.gg/momentummod"> contact us here!</a> Please include some sort of past work or proof of skills. We're accepting programmers, source level designers, 3d and 2d artists, as well as web developers.</p>
```

2022-10-01 20:21 UTC, Gocnak approved these changes

2022-10-01 20:21 UTC, merged